version: '3.7'

services:
  stanford_corenlp:
    build: stanford-corenlp/.
    ports:
      - "9000:9000"
    environment: 
      - JAVA_XMX=12G
      - ANNOTATORS=tokenize,ssplit,parse
    restart: always
