version: '3.7'

services:
  stanford_corenlp:
    build: d1egoprog/stanford-corenlp:4.5.2
    ports:
      - "9000:9000"
    environment: 
      - JAVA_XMX=12G
      - ANNOTATORS=tokenize,ssplit,parse
    restart: always
